name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '23'

    - name: Give execute permission to mvnw
      run: chmod +x ./mvnw

    - name: Build Java app
      run: ./mvnw clean package -DskipTests

      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/${{ secrets.GHCR_USERNAME }}/score-service:latest

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/score-service:latest
